ISO_COUNTRY_MAP = {
    "us": "United States",
    "usa": "United States",
    "united states": "United States",
    "united states of america": "United States",
    "uk": "United Kingdom",
    "gb": "United Kingdom",
    "gbr": "United Kingdom",
    "united kingdom": "United Kingdom",
    "ca": "Canada",
    "can": "Canada",
    "canada": "Canada",
    "de": "Germany",
    "deu": "Germany",
    "germany": "Germany",
    "fr": "France",
    "fra": "France",
    "france": "France",
    "in": "India",
    "ind": "India",
    "india": "India",
    "au": "Australia",
    "aus": "Australia",
    "australia": "Australia",
    "sg": "Singapore",
    "sgp": "Singapore",
    "singapore": "Singapore",
}
